# Generated by Django 3.0.7 on 2020-06-13 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='behavior',
            field=models.CharField(max_length=40, null=True, verbose_name='Поведение животного'),
        ),
        migrations.AddField(
            model_name='animals',
            name='gender',
            field=models.CharField(default='NULL', max_length=20, verbose_name='Пол'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animals',
            name='sort_animal',
            field=models.CharField(default='NULL', max_length=20, verbose_name='Вид животного'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='animals',
            name='special_signs',
            field=models.CharField(default='NULL', max_length=20, verbose_name='Особые приметы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='animals',
            name='PhotoUrl',
            field=models.ImageField(upload_to='static/setup_img/'),
        ),
        migrations.AlterField(
            model_name='request',
            name='photoURL',
            field=models.ImageField(blank=True, default='NULL', upload_to='requests/img'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='user_id',
            field=models.ForeignKey(on_delete=models.SET('Админ'), to=settings.AUTH_USER_MODEL, verbose_name='Ловец'),
        ),
    ]
