# Generated by Django 3.0.7 on 2020-06-13 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20200613_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Статус')),
            ],
        ),
        migrations.AlterField(
            model_name='animals',
            name='PhotoUrl',
            field=models.ImageField(blank=True, upload_to='static/setup_img'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='animal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_id', to='MainApp.Animals', verbose_name='Животное'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.ForeignKey(max_length=20, on_delete=models.SET('Неизвестно'), to='MainApp.Status', verbose_name='Статус'),
        ),
    ]
