# Generated by Django 3.0.7 on 2020-06-14 05:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0003_auto_20200614_0145'),
    ]

    operations = [

        migrations.AddField(
            model_name='animals',
            name='chip',
            field=models.CharField(max_length=50, null=True, verbose_name='Чип животного'),
        ),
        migrations.AlterField(
            model_name='animals',
            name='PhotoUrl',
            field=models.ImageField(blank=True, upload_to='static/requests/imgAnimal'),
        ),
        migrations.AlterField(
            model_name='request',
            name='photoURL',
            field=models.ImageField(blank=True, upload_to='static/requests/imgReq'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='user_id',
            field=models.ForeignKey(on_delete=models.SET('Null'), to=settings.AUTH_USER_MODEL, verbose_name='Ловец'),
        ),
        migrations.CreateModel(
            name='Lost_animals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('animal_id', models.ForeignKey(on_delete=models.SET('NULL'), related_name='animals_id', to='MainApp.Animals')),
                ('user_id', models.ForeignKey(on_delete=models.SET('NULL'), related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
