# Generated by Django 3.0.7 on 2020-06-14 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_auto_20200614_1048'),
    ]

    operations = [

    ]
