# Generated by Django 3.0.7 on 2020-06-14 00:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainApp', '0004_auto_20200614_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='chip',
            field=models.CharField(max_length=50, null=True, verbose_name='Чип животного'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='user_id',
            field=models.ForeignKey(on_delete=models.SET('Null'), to=settings.AUTH_USER_MODEL, verbose_name='Ловец'),
        ),
    ]
