# Generated by Django 3.0.7 on 2020-06-14 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_remove_transfer_animal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='animal_id',
        ),
    ]
