# Generated by Django 3.0.7 on 2020-06-14 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_remove_transfer_animal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='animals_id',
            field=models.ForeignKey(default=1, on_delete=models.SET('Null'), to='MainApp.Animals'),
            preserve_default=False,
        ),
    ]
